### PR TITLE
[vscode] Fix debugging in vscode ide

### PR DESCRIPTION
**Pull request by flplv**
[VSCODE only]
This CR fixes the error when we click the "Debug" decoration button on top of a `@(test)` decorated function;
it also activates vscode's support to add breakpoint to the language

### CODE REVIEW

**Comment by DanielGavin** [comment]
Sweet thanks. It seems the Ci is crashing on tests that has nothing to do with your changes. Not sure if this is something introduced with a new version of Odin.

**Comment by DanielGavin** [comment]
I'll make a new version of the extension.

**Comment by flplv** [comment]
wow that was fast...

**Comment by flplv** [comment]
I got one more commit that may be controversial.. I will open another PR now

**Pull request merged**
