### PR TITLE
[vscode] icon fix; plus small change

### PR DESCRIPTION
**Pull request by flplv**
and 
[minor] change the promise handling style of fs.stat

### CODE REVIEW

**Comment by flplv** [comment]
btw: feel free to reject, in case you want to maintain the ols.json location where it is.

I figured every extension in vscode uses the .vscode folder for settings so we'd like to do that too

**Comment by flplv** [comment]
Just pushed another patch fixing the file icon.
I chose the de-saturated blue from the odin website as color because it works ok for both light and dark themes

**Comment by DanielGavin** [comment]
We can't move the path of the `ols.json`, it is used to indicate the root of the project.

**Comment by flplv** [comment]
here it is a screenshot of how vscode looks now: 
Screenshot from 2022-09-19 16-47-40

**Comment by flplv** [comment]
another one with the debugging working :)
Screenshot from 2022-09-19 16-52-31

**Pull request merged**
